# Generated by Django 2.1.4 on 2020-05-14 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_product_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
    ]
