# Generated by Django 2.1.4 on 2020-05-16 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_product_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
    ]
