# Generated by Django 2.1.4 on 2020-05-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_remove_product_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(to='seller.Tag'),
        ),
    ]
