# Generated by Django 2.1.4 on 2020-05-11 16:15

import accounts.account_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200430_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='name',
            field=models.CharField(max_length=100, validators=[accounts.account_validation.validator.name]),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='phone',
            field=models.CharField(max_length=100, validators=[accounts.account_validation.validator.phone]),
        ),
    ]
